version: "3.8"

services:
  db:
    image: mysql:8.0.31
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./api/tmp/db:/var/lib/mysql"
      - "./my.cnf:/etc/mysql/conf.d/my.cnf"

  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - "./api:/$WORKDIR"
    depends_on:
      - db
    ports:
      - "$API_PORT:3000"

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        API_URL: "http://localhost:$API_PORT"
    command: yarn run dev
    volumes:
      - "./front:/$WORKDIR"
    ports:
      - "$FRONT_PORT:3000"
    depends_on:
      - api